services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./front
        target: /app
      - type: volume
        target: /app/node_modules
      - type: volume
        target: /app/.next
    ports:
      - 3000:3000

volumes:
  front_node_modules:
  front_next: